language: python
python:
  - "3.8"
  - "2.7"
install:
  - pip install coveralls
jobs:
  include:
    - language: python
script: coverage run --source=tauros_api -m pytest tests/ && COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
