language: python
python:
  - "3.8"
  - "2.7"
install:
  - pip install pytest==4.5.0
  - pip install codecov==2.0.15
  - pip install pytest-cov==2.7.1
jobs:
  include:
    - language: python
      script:
      - pytest --cov-report=xml --cov=tauros_api tests/
